[build]
  command = "npm run build"
  publish = "out"
  functions = './functions'

[dev]
  command = "npm run dev"
  framework = "#custom"
  port = 8888
  targetPort = 3000
  autoLaunch = true

[functions]
  directory = "functions/"    

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]    
from = '/api/*'
to = '/.netlify/functions/:splat'
status = 200